---
abstract: 'Just load plugins, aware of development directories'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Pluggable-Loader
provides:
  Module::Pluggable::Loader:
    file: lib/Module/Pluggable/Loader.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Pluggable: 0
  Scalar::Util: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Pluggable-Loader
  homepage: http://search.cpan.org/dist/Module-Pluggable-Loader/
  repository: http://github.com/hanekomu/Module-Pluggable-Loader
version: 1.100860
