---
abstract: 'just load plugins, aware of development directories'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Pluggable-Loader
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Module::Pluggable: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Module-Pluggable-Loader
  homepage: http://search.cpan.org/dist/Module-Pluggable-Loader/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/module-pluggable-loader.git
version: 0.01
